-- CreateTable
CREATE TABLE "User" (
    "id" STRING NOT NULL,
    "name" STRING NOT NULL,
    "email" STRING NOT NULL,
    "passwordHash" STRING NOT NULL,
    "role" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MenuItem" (
    "id" STRING NOT NULL,
    "title" STRING NOT NULL,
    "img" STRING NOT NULL,
    "description" STRING NOT NULL,
    "price" FLOAT8 NOT NULL,
    "type" STRING NOT NULL,

    CONSTRAINT "MenuItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Order" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "table" STRING NOT NULL,
    "customer" STRING NOT NULL,
    "status" STRING NOT NULL DEFAULT 'pending',
    "visible" BOOL NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Order_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MenuItemsInOrder" (
    "count" INT4 NOT NULL,
    "orderId" INT4 NOT NULL,
    "menuItemId" STRING NOT NULL,

    CONSTRAINT "MenuItemsInOrder_pkey" PRIMARY KEY ("orderId","menuItemId")
);

-- AddForeignKey
ALTER TABLE "MenuItemsInOrder" ADD CONSTRAINT "MenuItemsInOrder_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MenuItemsInOrder" ADD CONSTRAINT "MenuItemsInOrder_menuItemId_fkey" FOREIGN KEY ("menuItemId") REFERENCES "MenuItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
